cluster.name: "opensearch-cluster"
network.host: 0.0.0.0
discovery.type: single-node

# Disable security plugin for Magento connection
plugins.security.disabled: true

# Required for Magento 2.4.8+
compatibility.override_main_response_version: true
